    
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chaker
 */
public class Etudiant extends javax.swing.JFrame {

    /**
     * Creates new form Etudiant
     */
     ButtonGroup bg ;
    public Etudiant() {
        initComponents();
        Connection();
        remplirTable();
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(label_border);
        close.setBorder(label_border);
        bg = new ButtonGroup();
        bg.add(txtmasc);
        bg.add(txtfem);
    }
    Connection conn ;
    PreparedStatement st ;
    Statement set ;
    ResultSet rs ;
         public void Connection (){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/Etudiant", "root", "") ;
            System.out.println("Connexion avec succes");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
             
             
             
         }
         
 public ArrayList<Etudiantdata> retrieveData(){
     ArrayList<Etudiantdata> al=null ;
     al=new ArrayList<Etudiantdata>();
     try{
     String form="SELECT * FROM `student`;";
     set=conn.createStatement();
     rs=set.executeQuery(form);
     Etudiantdata etudiant;
     while(rs.next()){
         etudiant =new Etudiantdata(rs.getInt(1) ,rs.getString("nom"),rs.getString("prenom"),rs.getString("adresse_mail"),
                 rs.getString("telephone"),rs.getString(6),rs.getString(7),rs.getString(8));
     al.add(etudiant);
     }
     }catch(Exception e){
     System.out.println("Erreur de trouver les données: "+e);
     }
     return al ;
 }        
 public void remplirTable(){
     ArrayList<Etudiantdata> al= retrieveData();
     DefaultTableModel model=(DefaultTableModel)table.getModel();
     model.setRowCount(0);
     Object[] row=new Object[8];
     for(int i = 0; i < al.size(); i++){
         row[0]=al.get(i).getCin();
         row[1]=al.get(i).getNom();
         row[2]=al.get(i).getPrenom();
         row[3]=al.get(i).getAdresse_mail();
         row[4]=al.get(i).getTelephone();
         row[5]=al.get(i).getGenre();
         row[6]=al.get(i).getDate_naissance();
         row[7]=al.get(i).getNiveaux();
         model.addRow(row);
     }
 }
 public void showitem (int index){
     
     txtcin.setText(Integer.toString(retrieveData().get(index).getCin()));
     txtnom.setText(retrieveData().get(index).getNom());
     txtprenom.setText(retrieveData().get(index).getPrenom());
     txtadress.setText(retrieveData().get(index).getAdresse_mail());
     txtphone.setText(retrieveData().get(index).getTelephone());
    
     
     
     
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtcin = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtadress = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtmasc = new javax.swing.JRadioButton();
        txtfem = new javax.swing.JRadioButton();
        txtniveaux = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        txtcherchernom = new javax.swing.JTextField();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("GESTION DES ETUDIANTS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel2.setText("CIN :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 131, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 169, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setText("Prenom :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 207, 76, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel5.setText("adresse e-mail :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 245, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel6.setText("date de naissance :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 365, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel7.setText("Telephone :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel8.setText("Genre :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 322, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel9.setText("niveuax :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 401, -1, -1));

        txtcin.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtcin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcinKeyTyped(evt);
            }
        });
        jPanel1.add(txtcin, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 130, 140, -1));

        txtnom.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 168, 140, -1));

        txtprenom.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jPanel1.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 206, 140, -1));

        txtadress.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jPanel1.add(txtadress, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 244, 140, -1));

        txtphone.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtphoneKeyTyped(evt);
            }
        });
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 282, 140, -1));

        txtmasc.setSelected(true);
        txtmasc.setText("Masculin");
        jPanel1.add(txtmasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 320, -1, -1));

        txtfem.setText("Féminin");
        jPanel1.add(txtfem, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 320, -1, -1));

        txtniveaux.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtniveaux.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er ", "2eme", "3eme", "1er Mastère", "2eme Mastère" }));
        txtniveaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtniveauxActionPerformed(evt);
            }
        });
        jPanel1.add(txtniveaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 400, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIN", "Nom", "Prenom", "adresse e-mail", "Telephone", "Genre", "Date de Naissance", "Niveaux"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 130, 641, 215));

        ajouter.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 441, -1, -1));

        edit.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        edit.setText("Editer");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 441, 81, -1));

        supprimer.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel1.add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 441, -1, -1));

        txtcherchernom.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        txtcherchernom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcherchernomKeyReleased(evt);
            }
        });
        jPanel1.add(txtcherchernom, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 357, 119, -1));

        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 11, 24, -1));

        minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setText("-");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(975, 11, 24, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButton1.setText("Actualiser");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 479, 277, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel11.setText("Chercher par Nom :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/deco.png"))); // NOI18N
        jButton2.setText("Déconnexion");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, -1));
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 130, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backkk.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtnom.setText("");
        txtcin.setText("");
        txtdate.setDate(null);
        txtprenom.setText("");
        txtphone.setText("");
        txtadress.setText("");
        txtmasc.setSelected(true);
        txtfem.setSelected(false);
        txtniveaux.setSelectedIndex(0);
        //s bg.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        minimize.setBorder(label_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        minimize.setBorder(label_border);
        minimize.setForeground(Color.black);
    }//GEN-LAST:event_minimizeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        close.setBorder(label_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        close.setBorder(label_border);
        close.setForeground(Color.black);
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void txtcherchernomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcherchernomKeyReleased
        // TODO add your handling code here:
        ArrayList<Etudiantdata> al=null ;
        al=new ArrayList<Etudiantdata>();
        String val=txtcherchernom.getText().toString();
        try{
            String form="SELECT * FROM `student` where nom like '%"+val+"%' ;";
            set=conn.createStatement();
            rs=set.executeQuery(form);
            Etudiantdata etudiant;
            while(rs.next()){
                etudiant =new Etudiantdata(rs.getInt(1) ,rs.getString("nom"),rs.getString("prenom"),rs.getString("adresse_mail"),
                    rs.getString("telephone"),rs.getString("genre"),rs.getString(7),rs.getString("niveaux"));
                al.add(etudiant);
            }

            DefaultTableModel model=(DefaultTableModel)table.getModel();
            model.setRowCount(0);
            Object[] row=new Object[8];
            for(int i = 0; i < al.size(); i++){
                row[0]=al.get(i).getCin();
                row[1]=al.get(i).getNom();
                row[2]=al.get(i).getPrenom();
                row[3]=al.get(i).getAdresse_mail();
                row[4]=al.get(i).getTelephone();
                row[5]=al.get(i).getGenre();
                row[6]=al.get(i).getDate_naissance();
                row[7]=al.get(i).getNiveaux();
                model.addRow(row);
            }
        }catch(Exception e){
            System.out.println("Erreur de trouver les données: "+e);
        }
    }//GEN-LAST:event_txtcherchernomKeyReleased

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        if(txtcin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Entrer CIN", "Erreur", 2 );
        }else{ try {
            String del = "DELETE FROM `student` WHERE cin=?;";
            st = conn.prepareStatement(del);
            st.setInt(1, Integer.parseInt(txtcin.getText()));
            int res =st.executeUpdate();
            remplirTable();
            if(res>=1){
                JOptionPane.showMessageDialog(null, "Etudiant supprimé", "Suppression", 2 );
            }else{
                JOptionPane.showMessageDialog(null, "Erreur", "Erreur", 2 );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        txtnom.setText("");
        txtcin.setText("");
        txtdate.setDate(null);
        txtprenom.setText("");
        txtphone.setText("");
        txtadress.setText("");
        txtmasc.setSelected(true);
        txtfem.setSelected(false);
        txtniveaux.setSelectedIndex(0);
    }//GEN-LAST:event_supprimerActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String nom = txtnom.getText() ;
        String prenom = txtprenom.getText() ;
        String adresse_mail = txtadress.getText() ;
        String telephone = txtphone.getText() ;

        String genre = "Masculin";
        if(txtfem.isSelected()){
            genre = "Féminin";
        }
        String niveaux = txtniveaux.getSelectedItem().toString();
        if(nom.trim().equals("") || prenom.trim().equals("") || adresse_mail.trim().equals("") || telephone.trim().equals("")
        ){
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides", "champs vide", 2 );
        }

        else if(txtcin.getText()!=null || txtnom.getText()!=null || txtprenom.getText()!=null || txtadress.getText()!=null || txtphone.getText()!=null
            || txtdate!=null ){

            try {
                String sql2= "UPDATE `student` SET `nom`=?,`prenom`=?,`adresse_mail`=?,`telephone`=?,`genre`=?,`date_naissance`=?,`niveaux`=? WHERE `cin`=?;";
                st = conn.prepareStatement(sql2);

                st.setString(1, nom);
                st.setString(2, prenom);
                st.setString(3, adresse_mail);
                st.setString(4, telephone);
                st.setString(5, genre);
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
                String date_naissance =sdf.format(txtdate.getDate());
                st.setString(6, date_naissance);
                st.setString(7, niveaux);
                st.setInt(8, Integer.parseInt(txtcin.getText()));
                int res = st.executeUpdate();
                remplirTable();
                if(res<=1){
                    JOptionPane.showMessageDialog(null, "Edit avec Succéess", "Succéess", 2 );
                }else{
                    JOptionPane.showMessageDialog(null, "Edit echoué", "Erreur", 2 );
                }
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        txtnom.setText("");
        txtcin.setText("");
        txtdate.setDate(null);
        txtprenom.setText("");
        txtphone.setText("");
        txtadress.setText("");
        txtmasc.setSelected(true);
        txtfem.setSelected(false);
        txtniveaux.setSelectedIndex(0);
    }//GEN-LAST:event_editActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        String nom = txtnom.getText() ;
        String prenom = txtprenom.getText() ;
        String adresse_mail = txtadress.getText() ;
        String telephone = txtphone.getText() ;

        String genre = "Masculin";
        if(txtfem.isSelected()){
            genre = "Féminin";
        }
        String niveaux = txtniveaux.getSelectedItem().toString();
        if(nom.trim().equals("") || prenom.trim().equals("") || adresse_mail.trim().equals("") || telephone.trim().equals("")
        ){
            JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides", "champs vide", 2 );
        }else if(txtcin.getText()!=null || txtnom.getText()!=null || txtprenom.getText()!=null || txtadress.getText()!=null || txtphone.getText()!=null
            || txtdate!=null  ){
            String sql = "INSERT INTO `student`(`cin`, `nom`, `prenom`, `adresse_mail`, `telephone`, `genre`, `date_naissance`, `niveaux`) VALUES (?,?,?,?,?,?,?,?)";
            try {
                st = conn.prepareStatement(sql);
                st.setInt(1, Integer.parseInt(txtcin.getText()));
                st.setString(2, nom);
                st.setString(3, prenom);
                st.setString(4, adresse_mail);
                st.setString(5, telephone);
                st.setString(6, genre);
                try{
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
                    String date_naissance =sdf.format(txtdate.getDate());
                    st.setString(7, date_naissance);
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Un ou plusieurs champs sont vides", "champs vide", 2 );
                }

                st.setString(8, niveaux);
                int res = st.executeUpdate();
                remplirTable();
                if(res<=1){
                    JOptionPane.showMessageDialog(null, "Insertion avec Succéess", "Succéess", 2 );
                }else{
                    JOptionPane.showMessageDialog(null, "Insertion echoué", "Erreur", 2 );
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "CIN est déjà pris, choisi un autre", "CIN déja existe", 2 );
            }

        }

    }//GEN-LAST:event_ajouterActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked

        // TODO add your handling code here:
        int ind= table.getSelectedRow();
        showitem(ind);
        TableModel model = table.getModel();

        String genre = model.getValueAt(ind, 5).toString();
        if (genre.equals("Masculin")){
            txtmasc.setSelected(true);

        }else {
            txtfem.setSelected(true);

        }
        try {
            DefaultTableModel mod=(DefaultTableModel)table.getModel();
            java.util.Date dob=null;
            dob=new SimpleDateFormat("dd-MMM-yyyy").parse((String)mod.getValueAt(ind, 6));
            txtdate.setDate(dob);
        } catch (ParseException ex) {
            Logger.getLogger(Etudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        String niv = model.getValueAt(ind, 7).toString();
        switch (niv){
            case"1er":
            txtniveaux.setSelectedIndex(0);
            break;
            case"2eme":
            txtniveaux.setSelectedIndex(1);
            break;
            case"3eme":
            txtniveaux.setSelectedIndex(2);
            break;
            case"1er Mastère":
            txtniveaux.setSelectedIndex(3);
            break;
            case"2eme Mastère":
            txtniveaux.setSelectedIndex(4);
            break;
        }
    }//GEN-LAST:event_tableMouseClicked

    private void txtniveauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtniveauxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtniveauxActionPerformed

    private void txtphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtphoneKeyTyped

    private void txtcinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcinKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_txtcinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Etudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Etudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel close;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtadress;
    private javax.swing.JTextField txtcherchernom;
    private javax.swing.JTextField txtcin;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JRadioButton txtfem;
    private javax.swing.JRadioButton txtmasc;
    private javax.swing.JComboBox<String> txtniveaux;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
